stages:
  process:
    cmd: python src/process.py
    deps:
    - data/iris.csv
    - src/process.py
    params:
    - process.data_source
    - process.processed_data_source
    outs:
    - data/processed
